language: node_js
node_js:
- 8.15.0
script:
- npm run lint
- NODE_ENV=production npm run build
deploy:
  provider: gae
  keyfile: sbnaukma2-ce87eab4bc3e.json
  project: sbnaukma2
notifications:
  slack: sbteam-workspace:vN5MU2uVkGH03b8jtz6JzCJ0
before_install:
- openssl aes-256-cbc -K $encrypted_23672130aec4_key -iv $encrypted_23672130aec4_iv
  -in sbnaukma2-ce87eab4bc3e.json.enc -out sbnaukma2-ce87eab4bc3e.json -d
