export const Projects = [{
  id: 1,
  title: 'МОГИЛЯНСЬКИЙ ВЕРТЕП',
  img: '/images/project1.png',
  available: true,
  fbLink: '//facebook.com',
}, {
  id: 2,
  title: 'КОЛОДІЙ',
  img: '/images/project1.png',
  available: false,
  fbLink: '//facebook.com',
}, {
  id: 3,
  title: 'КУПАЛА',
  img: '/images/project2.png',
  available: true,
  fbLink: '//facebook.com',
}, {
  id: 4,
  title: 'МОГИЛЯНСЬКИЙ ВЕРТЕП',
  img: '/images/project1.png',
  available: true,
  fbLink: '//facebook.com',
}, {
  id: 5,
  title: 'КОЛОДІЙ',
  img: '/images/project1.png',
  available: false,
  fbLink: '//facebook.com',
}, {
  id: 6,
  title: 'КУПАЛА',
  img: '/images/project2.png',
  available: true,
  fbLink: '//facebook.com',
}];

export const Members = [{
  id: '1',
  name: 'Василій',
  surname: 'Іванов',
  nickName: 'Васив',
  avatar: 'http://lumpics.ru/wp-content/uploads/2017/11/Programmyi-dlya-sozdaniya-avatarok.png',
  degrees: [{
    year: '2010',
    faculty: 'ФІ',
    facultyId: '1',
    speciality: "Комп'ютерні науки",
    specialityId: '3',
    program: 'БП',
    programId: '1',
  }],
  patronId: '2',
  birthday: '1990-08-25',
  phones: ['0991234567'],
  profiles: ['gitlab.com'],
  emails: ['vasyaIvan@gmail.com'],
  positions: [{ years: [2011, 2012], name: 'голова' }],
  interests: ['football', 'reading'],
  projects: ['id1', 'id2'],
  status: 'BRATCHYK',
}, {
  id: '2',
  name: 'Петро',
  surname: 'Сидоров',
  nickName: 'Петрос',
  avatar: 'https://img.joinfo.ua/i/2017/11/5a12977d34baf.jpg',
  degrees: [{
    year: '2010',
    faculty: 'ФІ',
    facultyId: '1',
    speciality: "Комп'ютерні науки",
    specialityId: '3',
    program: 'БП',
    programId: '1',
  }],
  patronId: '-1',
  birthday: '1990-08-25',
  phones: ['0501234567'],
  profiles: ['github.com'],
  emails: ['petyaSidor@gmail.com'],
  positions: [{ years: [2011, 2012], name: 'qwerty' }],
  interests: ['football', 'reading'],
  projects: ['id1', 'id2'],
  status: 'POSHANOVANYJ',
},
{
  id: '3',
  name: 'Петро',
  surname: 'Сидоров',
  nickName: 'Петрос',
  avatar: 'https://img.joinfo.ua/i/2017/11/5a12977d34baf.jpg',
  degrees: [{
    year: '2010',
    faculty: 'ФІ',
    facultyId: '1',
    speciality: "Комп'ютерні науки",
    specialityId: '3',
    program: 'БП',
    programId: '1',
  }],
  patronId: '-1',
  birthday: '1990-08-25',
  phones: ['0501234567'],
  profiles: ['github.com'],
  emails: ['petyaSidor@gmail.com'],
  positions: [{ years: [2011, 2012], name: 'qwerty' }],
  interests: ['football', 'reading'],
  projects: ['id1', 'id2'],
  status: 'POSHANOVANYJ',
},
];
export const Roles = [{
  role: {
    admin: true,
    kek: false,
    lol: false,
  },
  email: ['rshchibrik@gmail.com'],
  password: ['Roma3228'],
}];
