export const Projects = [{
  id: 1,
  title: 'МОГИЛЯНСЬКИЙ ВЕРТЕП',
  img: 'images/project1.png',
  available: true,
  fbLink: '//facebook.com',
}, {
  id: 2,
  title: 'КОЛОДІЙ',
  img: 'images/project1.png',
  available: false,
  fbLink: '//facebook.com',
}, {
  id: 3,
  title: 'КУПАЛА',
  img: 'images/project2.png',
  available: true,
  fbLink: '//facebook.com',
}, {
  id: 4,
  title: 'МОГИЛЯНСЬКИЙ ВЕРТЕП',
  img: 'images/project1.png',
  available: true,
  fbLink: '//facebook.com',
}, {
  id: 5,
  title: 'КОЛОДІЙ',
  img: 'images/project1.png',
  available: false,
  fbLink: '//facebook.com',
}, {
  id: 6,
  title: 'КУПАЛА',
  img: 'images/project2.png',
  available: true,
  fbLink: '//facebook.com',
}];

export const Members = [{
  id: 1,
  name: 'Василій',
  surname: 'Іванов',
  nickName: 'Васив',
  avatar: 'http://lumpics.ru/wp-content/uploads/2017/11/Programmyi-dlya-sozdaniya-avatarok.png',
  degree: [{
    year: '2010',
    faculty: 'ФІ',
    speciality: "Комп'ютерні науки",
    program: 'БП',
  }],
  patron: 2,
  birth: '25.08.1990',
  phones: ['0991234567'],
  profiles: ['github.com'],
  emails: ['vasyaIvan@gmail.com'],
  position: [{ years: [2011, 2012], name: 'голова' }],
  interests: ['football', 'reading'],
  projects: ['id1', 'id2'],
}, {
  id: 2,
  name: 'Петро',
  surname: 'Сидоров',
  nickName: 'Петрос',
  avatar: 'https://img.joinfo.ua/i/2017/11/5a12977d34baf.jpg',
  degree: [{
    year: '2010',
    faculty: 'ФІ',
    speciality: "Комп'ютерні науки",
    program: 'БП',
  }],
  patron: -1,
  birth: '25.08.1990',
  phones: ['0991234567'],
  profiles: ['github.com'],
  emails: ['vasyaIvan@gmail.com'],
  position: [{ years: [2011, 2012], name: 'qwerty' }],
  interests: ['football', 'reading'],
  projects: ['id1', 'id2'],
}];
