export const Projects = [{
  id: 1,
  title: 'Project 1',
  img: '//i2.wp.com/kashmirreader.com/wp-content/uploads/2018/10/PHE-projects.jpg?fit=600%2C300&ssl=1',
  available: true,
  fbLink: '//facebook.com',
}, {
  id: 2,
  title: 'Project 2',
  img: '//i2.wp.com/kashmirreader.com/wp-content/uploads/2018/10/PHE-projects.jpg?fit=600%2C300&ssl=1',
  available: false,
  fbLink: '//facebook.com',
}, {
  id: 3,
  title: 'Project 3',
  img: '//i2.wp.com/kashmirreader.com/wp-content/uploads/2018/10/PHE-projects.jpg?fit=600%2C300&ssl=1',
  available: true,
  fbLink: '//facebook.com',
}, {
  id: 4,
  title: 'Project 4',
  img: '//i2.wp.com/kashmirreader.com/wp-content/uploads/2018/10/PHE-projects.jpg?fit=600%2C300&ssl=1',
  available: false,
  fbLink: '//facebook.com',
}, {
  id: 5,
  title: 'Project 5',
  img: '//i2.wp.com/kashmirreader.com/wp-content/uploads/2018/10/PHE-projects.jpg?fit=600%2C300&ssl=1',
  available: false,
  fbLink: '//facebook.com',
}];

export const Members = [{
  id: 1,
  name: 'Василій',
  surname: 'Іванов',
  nickName: 'Васив',
  avatar: 'http://lumpics.ru/wp-content/uploads/2017/11/Programmyi-dlya-sozdaniya-avatarok.png',
  degree: [{
    year: '2010',
    faculty: 'ФІ',
    speciality: "Комп'ютерні науки",
    program: 'БП',
  }],
  patron: 2,
  birth: '25.08.1990',
  phones: ['0991234567'],
  profiles: ['github.com'],
  emails: ['vasyaIvan@gmail.com'],
  position: [{ years: [2011, 2012], name: 'голова' }],
  interests: ['football', 'reading'],
  projects: ['id1', 'id2'],
}, {
  id: 2,
  name: 'Петро',
  surname: 'Сидоров',
  nickName: 'Васив',
  avatar: 'url',
  degree: [{
    year: '2010',
    faculty: 'ФІ',
    speciality: "Комп'ютерні науки",
    program: 'БП',
  }],
  patron: -1,
  birth: '25.08.1990',
  phones: ['0991234567'],
  profiles: ['github.com'],
  emails: ['vasyaIvan@gmail.com'],
  position: [{ years: [2011, 2012], name: 'qwerty' }],
  interests: ['football', 'reading'],
  projects: ['id1', 'id2'],
}];
